"""Executable spec of the `px` shell (pyto/src/pyto/px.py).

Every test here runs `px` the way a person runs it -- a subprocess, a record path,
stdout -- and compares the bytes to a file committed under `tests/fixtures/px/`.
That is the whole claim the task makes: each command's output is a *pure function
of its inputs*, so an expected file can be committed at all. A test that called
the command functions in-process would prove the rendering; only a subprocess
proves the command.

The two records are the ones every command is tested on:

* `experiments/students/evidence/run-1/record.json`     -- 5 invocations, 4 Ticks
* `experiments/grouped-ablation/evidence/run-1/record.json` -- 15 invocations, 4 Ticks

The fixtures were written by the first run of each command and then read back and
checked by hand; they are expected output, not a snapshot of whatever happened.

Mutation notes are attached to the tests that carry a real claim, naming the line
in `px.py` to change and what fails when it does. Three of them were run
(see `experiments/tasks/41/packet.md`).
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

PYTO_ROOT = Path(__file__).resolve().parents[1]
SRC = PYTO_ROOT / "src"
FIXTURES = Path(__file__).resolve().parent / "fixtures" / "px"

STUDENTS = PYTO_ROOT / "experiments" / "students" / "evidence" / "run-1" / "record.json"
ABLATION = PYTO_ROOT / "experiments" / "grouped-ablation" / "evidence" / "run-1" / "record.json"
# The third record: one `oc` invocation and one `fn`, so `px effects` has a ledger
# to print. Committed under fixtures/px/ rather than taken from an experiment,
# because no experiment performs effects yet -- written once by the program in
# `tests/fixture_effects.py` (task 49) and read here, never regenerated by a test.
EFFECTS_DEMO = FIXTURES / "effects-record.json"
# The Tick projection's other fixture (task 73): three Ticks, `parallel: true`,
# and a `latency_ms` on every Tick, so `px tick` exercises the "mode" and
# "latency_ms carried by the record" branches the students record never does.
PARALLEL_DEMO = PYTO_ROOT / "viewer" / "fixtures" / "parallel-demo.json"

# A digest that is not the students record's, fixed so `px diff`'s output is a
# pure function of its inputs here too.
FLIPPED = "f" * 64


def run_px(*args: str) -> subprocess.CompletedProcess:
    """`python -m pyto.px ...` in a subprocess, with a fixed environment.

    `PYTHONPATH` points at `src` so the test does not depend on the package being
    installed, and the environment is otherwise inherited; nothing `px` prints
    reads from it.
    """
    env = dict(os.environ)
    env["PYTHONPATH"] = os.pathsep.join([str(SRC), env.get("PYTHONPATH", "")]).rstrip(os.pathsep)
    return subprocess.run(
        [sys.executable, "-m", "pyto.px", *args],
        capture_output=True,
        text=True,
        env=env,
        cwd=str(PYTO_ROOT),
    )


class PxFixtures(unittest.TestCase):
    """Every command, on both records, byte for byte against a committed file."""

    maxDiff = None

    def assert_fixture(self, name: str, *args: str, exit_code: int = 0) -> str:
        result = run_px(*args)
        self.assertEqual(result.stderr, "", f"px {' '.join(args)} wrote to stderr")
        self.assertEqual(result.returncode, exit_code, f"px {' '.join(args)} exit code")
        expected = (FIXTURES / name).read_text(encoding="utf-8")
        self.assertEqual(result.stdout, expected, f"px {' '.join(args)} != fixtures/px/{name}")
        return result.stdout

    # --- ps -------------------------------------------------------------------

    def test_ps_students(self):
        self.assert_fixture("ps-students.txt", "ps", str(STUDENTS))

    def test_ps_ablation(self):
        self.assert_fixture("ps-ablation.txt", "ps", str(ABLATION))

    def test_ps_times_students(self):
        """`--times` is the only way a duration reaches stdout.

        Mutation: px.py `cmd_ps`, drop the `if args.times` guard on the `MS`
        column -- `test_ps_students` fails, because the durations appear without
        being asked for.
        """
        self.assert_fixture("ps-times-students.txt", "ps", str(STUDENTS), "--times")

    def test_ps_without_times_names_no_duration(self):
        """The claim behind the fixture, stated so a reader need not diff two files."""
        plain = run_px("ps", str(STUDENTS)).stdout
        self.assertNotIn("MS", plain)
        record = json.loads(STUDENTS.read_text(encoding="utf-8"))
        for tick in record["ticks"]:
            for inv in tick["invocations"]:
                self.assertNotIn(f"{inv['duration_ms']:.3f}", plain)

    # --- ls -------------------------------------------------------------------

    def test_ls_students(self):
        self.assert_fixture("ls-students.txt", "ls", str(STUDENTS))

    def test_ls_ablation(self):
        self.assert_fixture("ls-ablation.txt", "ls", str(ABLATION))

    def test_ls_prefix_ablation(self):
        self.assert_fixture(
            "ls-ablation-models.txt", "ls", str(ABLATION), "scratch.ablation.model"
        )

    def test_ls_is_sorted_and_carries_every_address_the_record_knows(self):
        """Sorted, and a superset of the record's own `parts` block.

        Mutation: px.py `cmd_ls`, `for address in sorted(rows_by_address)` ->
        `for address in rows_by_address` -- the fixtures fail on the ablation
        record, whose derived order is not its sorted order.
        """
        lines = run_px("ls", str(ABLATION)).stdout.splitlines()[1:]
        addresses = [line.split()[0] for line in lines]
        self.assertEqual(addresses, sorted(addresses))
        record = json.loads(ABLATION.read_text(encoding="utf-8"))
        self.assertEqual(set(record["parts"]) - set(addresses), set())

    def test_ls_shows_a_receipt_address_the_record_lists(self):
        """"every address the record knows" includes receipt addresses.

        Neither committed record lists one -- `run_record`'s part index is built
        from the testimony and the receipts, never from the store, so a pyto
        record names no receipt of its own (RECORD.md, "Receipts as Parts") --
        but another runtime's record may, and `parts` is where it would appear.

        Mutation: px.py `cmd_ls`, drop the union with `record["parts"]` -- the
        receipt row below disappears and the KIND column has nothing to say.
        """
        record = json.loads(STUDENTS.read_text(encoding="utf-8"))
        record["parts"]["px.receipt.students-homework.Parse.parse"] = {
            "written_by": None, "read_by": [], "preexisting": False
        }
        record["parts"]["px.receipt.earlier-run.Tick.id"] = {
            "written_by": None, "read_by": [], "preexisting": True
        }
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "with-receipts.json"
            path.write_text(json.dumps(record), encoding="utf-8")
            rows = [line.split() for line in run_px("ls", str(path)).stdout.splitlines()]
        self.assertIn(
            ["px.receipt.students-homework.Parse.parse", "receipt", "unknown"], rows
        )
        self.assertIn(["px.receipt.earlier-run.Tick.id", "receipt", "preexisting"], rows)
        self.assertIn(["px.students.roster", "part", "parse"], rows)

    # --- partness (task 75) ----------------------------------------------------

    def _record_with_a_part_binding(self):
        """The students record, Tick 2 (Letters) made to also read a
        ``proposal.*`` address -- a part, task 75 -- so its own produce
        (``px.students.letters``) becomes provisional, and Tick 3 (Histogram),
        which reads Letters' produce, becomes provisional transitively."""
        record = json.loads(STUDENTS.read_text(encoding="utf-8"))
        part_address = "proposal.neat.composition.blok.root.abc123def456"
        record["parts"][part_address] = {"written_by": None, "read_by": [], "preexisting": True}
        record["ticks"][2]["invocations"][0]["inputs"]["basis"] = f"px:{part_address}"
        return record, part_address

    def test_ls_shows_no_provisional_column_when_the_record_touches_no_part(self):
        """"a record with no parts shows none": the column is not merely blank,
        it does not exist -- `test_ls_students` above is the byte-stable proof."""
        out = run_px("ls", str(STUDENTS)).stdout
        self.assertNotIn("PROVISIONAL", out)
        self.assertNotIn("provisional", out)

    def test_ls_shows_a_provisional_part_and_its_basis(self):
        record, part_address = self._record_with_a_part_binding()
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "with-part.json"
            path.write_text(json.dumps(record), encoding="utf-8")
            rows = {line.split()[0]: line for line in run_px("ls", str(path)).stdout.splitlines()[1:]}
        self.assertIn(f"provisional (basis: {part_address})", rows["px.students.letters"])
        self.assertIn(f"provisional (basis: {part_address})", rows["px.students.histogram"])
        self.assertTrue(rows["px.students.roster"].rstrip().endswith("-"))

    def test_tick_lists_the_basis_line_only_when_provisional(self):
        record, part_address = self._record_with_a_part_binding()
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "with-part.json"
            path.write_text(json.dumps(record), encoding="utf-8")
            letters = run_px("tick", str(path), "Letters").stdout
            histogram = run_px("tick", str(path), "Histogram").stdout
            parse = run_px("tick", str(path), "Parse").stdout
            payload = json.loads(run_px("tick", str(path), "Letters", "--json").stdout)
        self.assertIn(f"  basis: {part_address}\n", letters)
        self.assertIn(f"  basis: {part_address}\n", histogram)
        self.assertNotIn("basis:", parse)
        self.assertEqual(payload["basis"], [part_address])

    def test_ls_prefix_is_a_filter_over_the_same_index(self):
        """The prefix narrows which rows print; column widths follow the rows that
        remain, which is why the fixtures are compared to files and not to each
        other."""
        addresses = lambda out: [line.split()[0] for line in out.splitlines()[1:]]
        full = addresses(run_px("ls", str(ABLATION)).stdout)
        filtered = addresses(run_px("ls", str(ABLATION), "scratch.ablation.score").stdout)
        self.assertEqual(len(filtered), 6)
        self.assertEqual(
            filtered, [a for a in full if a.startswith("scratch.ablation.score")]
        )

    # --- cat ------------------------------------------------------------------

    def test_cat_students_mean(self):
        self.assert_fixture("cat-students-mean.txt", "cat", str(STUDENTS), "px.students.mean")

    def test_cat_ablation_comparison(self):
        self.assert_fixture(
            "cat-ablation-comparison.txt", "cat", str(ABLATION), "scratch.ablation.comparison"
        )

    def test_cat_is_canonical_json_the_record_carries(self):
        """`px cat` reads the record's `value` field and re-spells it canonically.

        Mutation: px.py `canonical_json`, drop `sort_keys=True` -- this fails on
        the mean's `{mean, n, total}`, which the record stores in insertion order.
        """
        out = run_px("cat", str(STUDENTS), "px.students.mean").stdout
        record = json.loads(STUDENTS.read_text(encoding="utf-8"))
        value = record["ticks"][1]["invocations"][0]["value"]["data"]
        self.assertEqual(json.loads(out), value)
        self.assertEqual(out, json.dumps(value, indent=2, sort_keys=True) + "\n")

    def test_cat_says_not_carried_when_the_record_omits_the_value(self):
        """The `omitted` kind is a real record state (RECORD.md `value.kind`)."""
        record = json.loads(STUDENTS.read_text(encoding="utf-8"))
        record["ticks"][1]["invocations"][0]["value"] = {
            "kind": "omitted", "data": None, "note": "the runtime did not retain values"
        }
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "omitted.json"
            path.write_text(json.dumps(record), encoding="utf-8")
            result = run_px("cat", str(path), "px.students.mean")
        self.assertEqual(result.returncode, 0)
        self.assertEqual(result.stdout, "not carried: the runtime did not retain values\n")

    def test_cat_of_a_multi_produce_invocation_names_the_one_part(self):
        """A Calculation may publish several Parts (`{?} WhatIsATick`, owner
        2026-09-10), and then `value.data` is the mapping it returned, so `cat`
        must take the entry the address names and not print the whole mapping.

        Mutation: px.py `cmd_cat`, drop the `len(declared) > 1` branch -- this
        fails, and `px cat <a>` and `px cat <b>` print the same two-key object.
        """
        record = json.loads(STUDENTS.read_text(encoding="utf-8"))
        stats = record["ticks"][1]["invocations"][0]
        stats["into"] = ["px.students.mean", "px.students.n"]
        stats["actual_produces"] = ["px.students.mean", "px.students.n"]
        stats["writes"] = [
            {"address": "px.students.mean", "kind": "new-address"},
            {"address": "px.students.n", "kind": "new-address"},
        ]
        stats["value"] = {
            "kind": "json", "data": {"px.students.mean": 80.5, "px.students.n": 12}, "note": None
        }
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "multi.json"
            path.write_text(json.dumps(record), encoding="utf-8")
            mean = run_px("cat", str(path), "px.students.mean")
            n = run_px("cat", str(path), "px.students.n")
            listed = run_px("ls", str(path)).stdout
        self.assertEqual(mean.stdout, "80.5\n")
        self.assertEqual(n.stdout, "12\n")
        self.assertIn("px.students.n", listed)

    def test_cat_refuses_an_address_no_invocation_produced(self):
        result = run_px("cat", str(STUDENTS), "px.students.scores_csv")
        self.assertEqual(result.returncode, 2)
        self.assertEqual(result.stdout, "")
        self.assertIn("no invocation in this record produced", result.stderr)
        self.assertNotIn(str(PYTO_ROOT), result.stderr)

    # --- diff -----------------------------------------------------------------

    def test_diff_of_a_record_with_itself(self):
        self.assert_fixture("diff-students-students.txt", "diff", str(STUDENTS), str(STUDENTS))

    def test_diff_names_the_invocation_whose_digest_flipped(self):
        """The task's own check: one digest changed, exit 1, the id named.

        Mutation: px.py `cmd_diff`, return `EXIT_OK` instead of `EXIT_DIFFERENCE`
        -- this fails on the exit code while the text still matches, which is why
        both are asserted.
        """
        record = json.loads(STUDENTS.read_text(encoding="utf-8"))
        record["ticks"][1]["invocations"][0]["result_sha256"] = FLIPPED
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "flipped.json"
            path.write_text(json.dumps(record), encoding="utf-8")
            result = run_px("diff", str(STUDENTS), str(path))
        self.assertEqual(result.returncode, 1)
        expected = (FIXTURES / "diff-students-flipped.txt").read_text(encoding="utf-8")
        self.assertEqual(result.stdout, expected)
        self.assertIn("mean", result.stdout)
        self.assertNotIn(str(PYTO_ROOT), result.stdout)

    def test_diff_reports_added_removed_and_changed_reads(self):
        """The other three kinds of difference, in one record pair."""
        record = json.loads(STUDENTS.read_text(encoding="utf-8"))
        record["ticks"][2]["invocations"][0]["id"] = "letters2"  # removed + added
        record["ticks"][3]["invocations"][0]["inputs"] = {"letters": "fn:parse"}  # reads changed
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "shuffled.json"
            path.write_text(json.dumps(record), encoding="utf-8")
            result = run_px("diff", str(STUDENTS), str(path))
        self.assertEqual(result.returncode, 1)
        lines = result.stdout.splitlines()
        self.assertIn("added    letters2  tick 2 Letters", lines)
        self.assertIn("removed  letters  tick 2 Letters", lines)
        self.assertIn("reads    histogram  -px.students.letters +px.students.roster", lines)

    def test_diff_ignores_durations(self):
        """Two records that differ only in how long they took are not different.

        Every Tick's `latency_ms`/`mode` changes with the durations too (the
        record's own accounting), but `tick_diff_rows` never compares either --
        RECORD.md: the schedule is not the program -- so every Tick still reads
        `same` and the invocation section still prints nothing.

        Mutation: px.py `cmd_diff`, compare `duration_ms` as well -- this fails,
        and every rerun of a deterministic program becomes a difference.
        """
        record = json.loads(STUDENTS.read_text(encoding="utf-8"))
        for tick in record["ticks"]:
            for inv in tick["invocations"]:
                inv["duration_ms"] = 99.0
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "slow.json"
            path.write_text(json.dumps(record), encoding="utf-8")
            result = run_px("diff", str(STUDENTS), str(path))
        self.assertEqual(result.returncode, 0)
        self.assertNotIn("differs", result.stdout)
        self.assertNotIn("only in", result.stdout)
        for tick in record["ticks"]:
            self.assertIn(f"{tick['name']}", result.stdout)
        self.assertTrue(result.stdout.endswith("no differences\n"))

    # --- laws -----------------------------------------------------------------

    def test_laws_students(self):
        self.assert_fixture("laws-students.txt", "laws", str(STUDENTS))

    def test_laws_ablation(self):
        self.assert_fixture("laws-ablation.txt", "laws", str(ABLATION))

    def test_laws_times_students(self):
        self.assert_fixture("laws-times-students.txt", "laws", str(STUDENTS), "--times")

    def test_laws_reads_a_sibling_read_as_a_chain_not_a_violation(self):
        """A read of an earlier sibling inside one Tick is a chain: the Tick runs
        in order and the node law holds (the owner, 2026-09-10: "'Calculations
        inside a Tick must be independent' was added as a rule, while your
        existing ChainSpot program deliberately chains dependent Calculations
        inside a Tick").

        Mutation: px.py `cmd_laws`, drop the `modes["chain"]` guard -- the
        students fixture then grows a `(4 parallel, 0 chain)` suffix and
        `test_laws_students` fails.
        """
        record = json.loads(STUDENTS.read_text(encoding="utf-8"))
        # median, in Tick 1, made to read its sibling mean's result.
        record["ticks"][1]["invocations"][1]["inputs"] = {"roster": "fn:mean"}
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "chained.json"
            path.write_text(json.dumps(record), encoding="utf-8")
            result = run_px("laws", str(path))
            times = run_px("laws", str(path), "--times")
        self.assertEqual(result.returncode, 0)
        self.assertIn("node law: ok (3 parallel, 1 chain)", result.stdout)
        self.assertNotIn("VIOLATION", result.stdout)
        # A chain runs in order, so the Tick's latency is its work, and only that
        # Tick's line says so.
        self.assertIn("Tick 1: work_ms=0.041 latency_ms=0.041 chain\n", times.stdout)
        self.assertIn("Tick 0: work_ms=0.030 latency_ms=0.030\n", times.stdout)

    def test_laws_exits_one_on_a_backwards_read(self):
        """A read of a sibling declared after the reader is still a node-law
        violation: the sequence inside a Tick runs in declared order, and this
        Calculation would read a Part nobody has produced yet.

        Mutation: px.py `cmd_laws`, `return EXIT_OK` unconditionally -- this
        fails while `test_laws_students` still passes.
        """
        record = json.loads(STUDENTS.read_text(encoding="utf-8"))
        # mean, first in Tick 1, made to read its later sibling median's result.
        record["ticks"][1]["invocations"][0]["inputs"] = {"roster": "fn:median"}
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "backwards.json"
            path.write_text(json.dumps(record), encoding="utf-8")
            result = run_px("laws", str(path))
        self.assertEqual(result.returncode, 1)
        self.assertIn("node law: 1 violation(s) (3 parallel, 1 chain)", result.stdout)
        self.assertIn(
            "VIOLATION node: node law violation: mean reads a sibling declared after it: "
            "px.students.median from median in Tick 1",
            result.stdout,
        )

    def test_laws_prints_no_path(self):
        """`tick_laws` echoes the path it was handed; `px` names the pcr instead.

        Mutation: px.py `cmd_laws`, print `args.record` instead of
        `record['pcr']` -- the fixture fails on any machine but the one that
        wrote it, which is the whole reason the line is there.
        """
        out = run_px("laws", str(STUDENTS)).stdout
        self.assertNotIn(str(PYTO_ROOT), out)
        self.assertIn("pcr: students-homework", out)

    # --- receipts -------------------------------------------------------------

    def test_receipts_students(self):
        self.assert_fixture("receipts-students.txt", "receipts", str(STUDENTS))

    def test_receipts_ablation(self):
        self.assert_fixture("receipts-ablation.txt", "receipts", str(ABLATION))

    def test_receipts_tick_students(self):
        self.assert_fixture(
            "receipts-students-stats.txt", "receipts", str(STUDENTS), "--tick", "Stats"
        )

    def test_receipts_show_declared_beside_actual(self):
        """The pair the format exists for: a result read declares nothing and
        touches the store not at all, so both of its columns are empty while its
        writes are not (RECORD.md, `declared_consumes`).
        """
        rows = [line.split() for line in run_px("receipts", str(STUDENTS)).stdout.splitlines()]
        parse = next(row for row in rows if row[1] == "parse")
        mean = next(row for row in rows if row[1] == "mean")
        self.assertEqual(parse[2:6], [
            "px:px.students.scores_csv", "px.students.scores_csv",
            "px.students.roster", "px.students.roster:new-address",
        ])
        self.assertEqual(mean[2:6], [
            "-", "-", "px.students.mean", "px.students.mean:new-address",
        ])


    # --- effects --------------------------------------------------------------

    def test_effects_demo(self):
        """The committed record of an `oc` run, one line per recorded effect."""
        self.assert_fixture("effects-demo.txt", "effects", str(EFFECTS_DEMO))

    def test_effects_tick_summarize(self):
        """`--tick` filters by Tick name: the pure Tick performed none, and says so."""
        self.assert_fixture(
            "effects-demo-summarize.txt", "effects", str(EFFECTS_DEMO), "--tick", "Summarize"
        )

    def test_effects_of_a_record_that_has_none(self):
        """A record whose run performed no effects prints the header and nothing else.

        Nothing is invented for it: `effects` is optional in the format (RECORD.md,
        "Effects") and absent means the run performed none.
        """
        self.assert_fixture("effects-students.txt", "effects", str(STUDENTS))

    def test_effects_rows_are_the_ledger_in_order_with_its_digests(self):
        """The claim behind the fixture: index is the position in that invocation's
        ledger, and the digest column is the record's `result_sha256`, unmodified.

        Mutation: px.py `cmd_effects`, `enumerate(...)` -> `enumerate(..., start=1)`
        -- the fixture fails, and a refusal from `ReplayEffects` (which names the
        index) would no longer line up with what `px` prints.
        """
        record = json.loads(EFFECTS_DEMO.read_text(encoding="utf-8"))
        ledger = record["ticks"][0]["invocations"][0]["effects"]
        rows = [line.split() for line in run_px("effects", str(EFFECTS_DEMO)).stdout.splitlines()]
        self.assertEqual(len(rows), len(ledger) + 1)  # + the header
        for position, (row, entry) in enumerate(zip(rows[1:], ledger)):
            self.assertEqual(row[1], "stamp")
            self.assertEqual(row[2], str(position))
            self.assertEqual(row[3], entry["kind"])
            self.assertEqual(row[-1], entry["result_sha256"])
        self.assertIn("out/note.txt", run_px("effects", str(EFFECTS_DEMO)).stdout)

    def test_effects_prints_no_absolute_path_and_no_recorded_value(self):
        """Paths are relative in the record, and a value is not a summary of a call.

        The clock reading and the draws are in the record (a replay needs them);
        `px effects` prints the digest, so a ledger can be read at a glance without
        the values scrolling past.
        """
        stdout = run_px("effects", str(EFFECTS_DEMO)).stdout
        record = json.loads(EFFECTS_DEMO.read_text(encoding="utf-8"))
        self.assertNotIn(str(PYTO_ROOT), stdout)
        self.assertNotIn("/tmp", stdout)
        for entry in record["ticks"][0]["invocations"][0]["effects"]:
            if entry["kind"] == "now_ms":
                self.assertNotIn(str(entry["result"]), stdout)

    # --- tick -------------------------------------------------------------
    #
    # fixtures/px/tick-students.txt and fixtures/px/tick-parallel-demo.txt, like
    # every other fixture in this file (module docstring above): written by the
    # first run of the command and read back and checked by hand, regenerated
    # the same way --
    #   PYTHONPATH=src python -m pyto.px tick <record> > tests/fixtures/px/tick-<name>.txt

    def test_tick_students(self):
        self.assert_fixture("tick-students.txt", "tick", str(STUDENTS))

    def test_tick_parallel_demo(self):
        self.assert_fixture("tick-parallel-demo.txt", "tick", str(PARALLEL_DEMO))

    def test_tick_is_byte_identical_run_twice_on_both_fixtures(self):
        """The task's own check: same record, same bytes, on both fixtures."""
        for record in (STUDENTS, PARALLEL_DEMO):
            with self.subTest(record=record.name):
                first, second = run_px("tick", str(record)), run_px("tick", str(record))
                self.assertEqual(first.stdout, second.stdout)
                self.assertEqual(first.returncode, 0)

    def test_tick_named_selects_the_one_block(self):
        """A name or an index prints exactly that Tick's block, and nothing else."""
        by_name = run_px("tick", str(STUDENTS), "Stats").stdout
        by_index = run_px("tick", str(STUDENTS), "1").stdout
        self.assertEqual(by_name, by_index)
        self.assertTrue(by_name.startswith("Tick 1 Stats\n"))
        self.assertNotIn("Parse", by_name)
        self.assertNotIn("Letters", by_name)

    def test_tick_names_an_unknown_selector(self):
        result = run_px("tick", str(STUDENTS), "NoSuchTick")
        self.assertEqual(result.returncode, 2)
        self.assertIn("NoSuchTick", result.stderr)
        self.assertNotIn(str(PYTO_ROOT), result.stderr)

    def test_tick_json_matches_the_text_projection(self):
        """`--json` carries the same facts `--times`-free text printed, structured."""
        payload = json.loads(run_px("tick", str(STUDENTS), "Stats", "--json").stdout)
        self.assertEqual(payload["index"], 1)
        self.assertEqual(payload["name"], "Stats")
        self.assertEqual(payload["consumes"], ["px.students.roster"])
        self.assertEqual(payload["internal"], [])
        self.assertEqual(
            payload["calculations"], ["fn.students.mean@52c2348bf909", "fn.students.median@e40b65bbc48b"]
        )
        self.assertEqual(payload["mode"], "serial")

    def test_tick_an_unchained_tick_has_an_empty_internal_list_and_consumes_the_rest(self):
        """The students record chains no Tick: every Tick's `internal` is empty and
        `consumes` carries the whole read set, exactly the case
        `tick_projection` degenerates to when nothing is produced and consumed
        inside one Tick.
        """
        record = json.loads(STUDENTS.read_text(encoding="utf-8"))
        payload = json.loads(run_px("tick", str(STUDENTS), "--json").stdout)
        by_name = {tick["name"]: tick for tick in payload}
        self.assertEqual(by_name["Stats"]["internal"], [])
        self.assertEqual(by_name["Stats"]["consumes"], ["px.students.roster"])
        for tick in record["ticks"]:
            with self.subTest(tick=tick["name"]):
                self.assertEqual(by_name[tick["name"]]["internal"], [])

    def test_tick_the_chain_tick_of_a_chained_record_lists_its_internal_link(self):
        """`median`, made to read `mean`'s result inside Stats, turns the Tick into
        a chain (the owner, 2026-09-10: "your existing ChainSpot program
        deliberately chains dependent Calculations inside a Tick" --
        research/chainspot-stages-ticks.md): the produced-and-consumed address is
        `internal`, and `consumes` excludes it -- the Tick still reads
        `px.students.roster` from Parse, but no longer lists `px.students.mean`
        as something it reads from outside itself.

        Mutation: px.py `tick_projection`, `reads & produced` -> `reads` alone
        for `internal` -- this still passes (mean is still in the read set), but
        `test_tick_an_unchained_tick_has_an_empty_internal_list_and_consumes_the_rest`
        fails, since every Tick's internal would then equal its full read set.
        """
        record = json.loads(STUDENTS.read_text(encoding="utf-8"))
        record["ticks"][1]["invocations"][1]["inputs"] = {"roster": "fn:mean"}
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "chained.json"
            path.write_text(json.dumps(record), encoding="utf-8")
            text = run_px("tick", str(path), "Stats").stdout
            payload = json.loads(run_px("tick", str(path), "Stats", "--json").stdout)
        self.assertEqual(payload["internal"], ["px.students.mean"])
        self.assertEqual(payload["consumes"], ["px.students.roster"])
        self.assertNotIn("px.students.mean", payload["consumes"], "consumes excludes internal")
        self.assertIn("  internal: px.students.mean\n", text)
        self.assertIn("  consumes: px.students.roster\n", text)


class PxDiffTicks(unittest.TestCase):
    """The Tick-by-Tick section `px diff` prints before its invocation section."""

    def test_two_identical_records_show_every_tick_as_same(self):
        out = run_px("diff", str(STUDENTS), str(STUDENTS)).stdout
        rows = [line.split() for line in out.splitlines()[1:5]]
        self.assertEqual([row[0] for row in rows], ["Parse", "Stats", "Letters", "Histogram"])
        self.assertTrue(all(row[1] == "same" for row in rows))

    def test_a_change_confined_to_one_tick_differs_in_only_that_tick(self):
        """Two records differing in one Tick, and only it: `Stats`' digest flips,
        so `Stats` reads `differs` and `Parse`, `Letters` and `Histogram` --
        untouched -- all read `same`.
        """
        record = json.loads(STUDENTS.read_text(encoding="utf-8"))
        record["ticks"][1]["invocations"][0]["result_sha256"] = FLIPPED
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "flipped.json"
            path.write_text(json.dumps(record), encoding="utf-8")
            result = run_px("diff", str(STUDENTS), str(path))
        self.assertEqual(result.returncode, 1)
        rows = {line.split()[0]: line.split()[1] for line in result.stdout.splitlines()[1:5]}
        self.assertEqual(rows, {"Parse": "same", "Stats": "differs", "Letters": "same", "Histogram": "same"})
        self.assertIn("Stats      differs  produces", result.stdout)

    def test_a_tick_renamed_is_only_in_a_and_only_in_b(self):
        """A Tick present in one record and not the other by name -- here, a rename
        -- is neither `same` nor `differs`: it is `only in a` for the name that
        vanished and `only in b` for the name that appeared, and the run as a
        whole still differs.
        """
        record = json.loads(STUDENTS.read_text(encoding="utf-8"))
        record["ticks"][1]["name"] = "Statistics"
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "renamed.json"
            path.write_text(json.dumps(record), encoding="utf-8")
            result = run_px("diff", str(STUDENTS), str(path))
        self.assertEqual(result.returncode, 1)
        lines = result.stdout.splitlines()
        self.assertTrue(any(line.startswith("Stats ") and "only in a" in line for line in lines))
        self.assertTrue(any(line.startswith("Statistics") and "only in b" in line for line in lines))


class PxShell(unittest.TestCase):
    """The shell around the six commands."""

    def test_help_lists_the_six_commands(self):
        result = run_px("--help")
        self.assertEqual(result.returncode, 0)
        for command in ("ps", "ls", "cat", "diff", "laws", "receipts"):
            with self.subTest(command=command):
                self.assertRegex(result.stdout, rf"(?m)^\s+{command}\s")

    def test_no_command_prints_help_and_exits_two(self):
        result = run_px()
        self.assertEqual(result.returncode, 2)
        self.assertIn("ps", result.stdout)

    def test_a_file_that_is_not_a_record_is_refused_by_the_shared_validator(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "nope.json"
            path.write_text('{"schema": "not-a-record"}', encoding="utf-8")
            result = run_px("ps", str(path))
        self.assertEqual(result.returncode, 2)
        self.assertIn("is not a pyto-run-record@1", result.stderr)
        self.assertIn("nope.json", result.stderr)
        self.assertNotIn(str(PYTO_ROOT), result.stderr)

    def test_a_missing_file_names_the_file_and_not_its_path(self):
        result = run_px("ps", str(PYTO_ROOT / "no" / "such" / "record.json"))
        self.assertEqual(result.returncode, 2)
        self.assertIn("record.json", result.stderr)
        self.assertNotIn(str(PYTO_ROOT), result.stderr)

    def test_every_command_is_a_pure_function_of_its_inputs(self):
        """Run each command twice and compare: the point of the whole file."""
        invocations = [
            ("ps", str(STUDENTS)),
            ("ps", str(ABLATION), "--times"),
            ("ls", str(STUDENTS)),
            ("cat", str(STUDENTS), "px.students.roster"),
            ("diff", str(STUDENTS), str(ABLATION)),
            ("laws", str(ABLATION), "--times"),
            ("receipts", str(ABLATION)),
        ]
        for args in invocations:
            with self.subTest(command=args[0]):
                first, second = run_px(*args), run_px(*args)
                self.assertEqual(first.stdout, second.stdout)
                self.assertEqual(first.returncode, second.returncode)

    def test_px_imports_no_kernel_runtime(self):
        """The design constraint: `px` reads JSON, and the only pyto modules it
        may import are the two shared readers it loads by path.

        Mutation: px.py, add `from .pcr import PCR` -- this fails.
        """
        source = (PYTO_ROOT / "src" / "pyto" / "px.py").read_text(encoding="utf-8")
        for forbidden in ("from .pcr", "from .core", "from .pql", "from .materialize",
                          "import pyto.pcr", "import pyto.core"):
            with self.subTest(forbidden=forbidden):
                self.assertNotIn(forbidden, source)

    def test_the_console_script_is_registered(self):
        pyproject = (PYTO_ROOT / "pyproject.toml").read_text(encoding="utf-8")
        self.assertIn("[project.scripts]", pyproject)
        self.assertIn('px = "pyto.px:main"', pyproject)


if __name__ == "__main__":
    unittest.main()
