/**
 * The `.mmd` sources of the Stages this port invents, embedded as data.
 *
 * `src/lab/source-data.js` does this for the LAB's own documents and says why:
 * the Stage modules are the same modules node runs and the browser imports, so
 * none of them may reach for node:fs at import time. S4, S5 and S6 have no
 * ChainSpot original -- they are written here -- so their flowcharts live under
 * `src/lab/stages/` and travel beside the code as the text below.
 * tests/lab-s5.test.js checks every entry against the file, so the two cannot
 * drift, exactly as tests/lab-source-data.test.js does for the LAB's.
 */
export const STAGE_TEXT = Object.freeze({
  "HolesByNearestAnchor.args.json": "{\n  \"bindAnchors\": { \"rule\": \"nearest-free-in-badge-order\" }\n}\n",
  "HolesByNearestAnchor.mmd": "flowchart TD\n    badges[\"px.badges.objects\"]\n    tees[\"px.tees\"]\n    baskets[\"px.baskets\"]\n\n    subgraph Holes[\"PCR: HolesByNearestAnchor\"]\n        subgraph ReadNumbers[\"Tick: Hole.readNumbers\"]\n            readNumbers[\"fn.Hole.readNumbers\"]\n        end\n        subgraph BindAnchors[\"Tick: Hole.bindAnchors\"]\n            bindAnchors[\"fn.Hole.bindAnchors\"]\n        end\n        subgraph Assemble[\"Tick: Hole.assemble\"]\n            assemble[\"fn.Hole.assemble\"]\n        end\n        subgraph Unplaced[\"Tick: Hole.unplaced\"]\n            unplaced[\"fn.Hole.unplaced\"]\n        end\n    end\n\n    badges -->|badges| readNumbers\n    readNumbers --> numbers[\"px.holes.numbers\"]\n    numbers -->|numbers| bindAnchors\n    tees -->|tees| bindAnchors\n    baskets -->|baskets| bindAnchors\n    bindAnchors --> binding[\"px.holes.binding\"]\n    binding -->|binding| assemble\n    assemble --> objects[\"px.holes.objects\"]\n    binding -->|binding| unplaced\n    objects -->|holes| unplaced\n    unplaced --> unplacedPart[\"px.holes.unplaced\"]\n",
  "S4.args.json": "{\n  \"badges\": {\n    \"knobs\": {\n      \"plateMinWidth\": 34,\n      \"plateMaxWidth\": 78,\n      \"plateMinHeight\": 24,\n      \"plateMaxHeight\": 54,\n      \"plateAspectMin\": 1,\n      \"plateAspectMax\": 2.4,\n      \"plateFillMin\": 0.55,\n      \"plateInteriorMargin\": 4,\n      \"plateGlyphFractionMin\": 0.04,\n      \"plateGlyphFractionMax\": 0.4,\n      \"plateProximityThreshold\": 22,\n      \"plateBboxMargin\": 4\n    },\n    \"digitKnobs\": {\n      \"minComponentArea\": 6,\n      \"heightRatioMin\": 0.5,\n      \"wideRatio\": 0.95,\n      \"valleySearchLo\": 0.3,\n      \"valleySearchHi\": 0.7,\n      \"digitW\": 24,\n      \"digitH\": 32,\n      \"confidenceFloorDivisor\": 8,\n      \"labelAmbiguityMargin\": 0.045\n    }\n  }\n}\n",
  "S4.mmd": "flowchart TD\n    components[\"px.components\"]\n    cleanBadges[\"px.badges.objects\"]\n    cleanBaskets[\"px.baskets\"]\n    cleanTees[\"px.tees\"]\n    shellFamily[\"px.baskets.shellFamily\"]\n    model[\"px.s1.whiteDigits.model\"]\n\n    subgraph S4[\"PCR: S4\"]\n        subgraph Unclaimed[\"Tick: Recover.unclaimed\"]\n            unclaimed[\"fn.Recover.unclaimed\"]\n        end\n        subgraph Badges[\"Tick: Recover.badges\"]\n            badges[\"fn.Recover.badges\"]\n        end\n        subgraph Baskets[\"Tick: Recover.baskets\"]\n            baskets[\"fn.Recover.baskets\"]\n        end\n        subgraph Tees[\"Tick: Recover.tees\"]\n            tees[\"fn.Recover.tees\"]\n        end\n        subgraph Ledger[\"Tick: Recover.ledger\"]\n            ledger[\"fn.Recover.ledger\"]\n        end\n    end\n\n    components -->|fields| unclaimed\n    cleanBadges -->|badges| unclaimed\n    cleanBaskets -->|baskets| unclaimed\n    cleanTees -->|tees| unclaimed\n    unclaimed --> unclaimedPart[\"px.recovered.unclaimed\"]\n    cleanBadges -->|badges| badges\n    unclaimedPart -->|unclaimed| badges\n    components -->|fields| badges\n    model -->|model| badges\n    badges --> recoveredBadges[\"px.recovered.badges\"]\n    cleanBaskets -->|baskets| baskets\n    unclaimedPart -->|unclaimed| baskets\n    shellFamily -->|shellFamily| baskets\n    components -->|fields| baskets\n    baskets --> recoveredBaskets[\"px.recovered.baskets\"]\n    cleanTees -->|tees| tees\n    unclaimedPart -->|unclaimed| tees\n    components -->|fields| tees\n    tees --> recoveredTees[\"px.recovered.tees\"]\n    recoveredBadges -->|badges| ledger\n    recoveredBaskets -->|baskets| ledger\n    recoveredTees -->|tees| ledger\n    unclaimedPart -->|unclaimed| ledger\n    ledger --> ledgerPart[\"px.recovered.ledger\"]\n",
  "S5.args.json": "{\n  \"pointing\": { \"minLeanPx\": 0.5 },\n  \"castRay\": { \"stepPx\": 1 }\n}\n",
  "S5.mmd": "flowchart TD\n    tees[\"px.recovered.tees\"]\n    badges[\"px.recovered.badges\"]\n    components[\"px.components\"]\n    canonical[\"px.course.canonicalPixels\"]\n\n    subgraph S5[\"PCR: S5\"]\n        subgraph Pointing[\"Tick: Tee.pointing\"]\n            pointing[\"fn.Tee.pointing\"]\n        end\n        subgraph CastRay[\"Tick: Tee.castRay\"]\n            castRay[\"fn.Tee.castRay\"]\n        end\n        subgraph Pair[\"Tick: TeeBadge.pair\"]\n            pair[\"fn.TeeBadge.pair\"]\n        end\n    end\n\n    tees -->|tees| pointing\n    components -->|fields| pointing\n    pointing --> pointingPart[\"px.teebadge.pointing\"]\n    pointingPart -->|pointing| castRay\n    badges -->|badges| castRay\n    canonical -->|raster| castRay\n    castRay --> hits[\"px.teebadge.hits\"]\n    pointingPart -->|pointing| pair\n    hits -->|hits| pair\n    badges -->|badges| pair\n    pair --> rays[\"px.teebadge.rays\"]\n",
  "S6.args.json": "{\n  \"continueRay\": { \"stepPx\": 1, \"maxResidualPx\": 12 }\n}\n",
  "S6.mmd": "flowchart TD\n    rays[\"px.teebadge.rays\"]\n    baskets[\"px.recovered.baskets\"]\n    badges[\"px.recovered.badges\"]\n\n    subgraph S6[\"PCR: S6\"]\n        subgraph ContinueRay[\"Tick: Hole.continueRay\"]\n            continueRay[\"fn.Hole.continueRay\"]\n        end\n        subgraph Straight[\"Tick: Hole.straight\"]\n            straight[\"fn.Hole.straight\"]\n        end\n        subgraph Unresolved[\"Tick: Hole.unresolved\"]\n            unresolved[\"fn.Hole.unresolved\"]\n        end\n    end\n\n    rays -->|rays| continueRay\n    baskets -->|baskets| continueRay\n    continueRay --> hits[\"px.holes.rayhits\"]\n    hits -->|hits| straight\n    rays -->|rays| straight\n    straight --> straightHoles[\"px.holes.straight\"]\n    hits -->|hits| unresolved\n    rays -->|rays| unresolved\n    badges -->|badges| unresolved\n    baskets -->|baskets| unresolved\n    straightHoles -->|holes| unresolved\n    unresolved --> unresolvedPart[\"px.holes.unresolved\"]\n",
  "S7.course.args.json": "{\n  \"obstacleMap\": { \"cellPx\": 16 },\n  \"graph\": { \"course\": \"labfixture\" }\n}\n",
  "S7.course.mmd": "flowchart TD\n    holes[\"px.holes.straight\"]\n    unresolvedHoles[\"px.holes.unresolved\"]\n    canonical[\"px.course.canonicalPixels\"]\n    remaining[\"px.remaining.afterBadges\"]\n    components[\"px.components\"]\n    baskets[\"px.baskets\"]\n    tees[\"px.tees\"]\n\n    subgraph Course[\"PCR: S7.course\"]\n        subgraph HoleGeometry[\"Tick: Course.holeGeometry\"]\n            holeGeometry[\"fn.Course.holeGeometry\"]\n        end\n        subgraph ObstacleMap[\"Tick: Course.obstacleMap\"]\n            obstacleMap[\"fn.Course.obstacleMap\"]\n        end\n        subgraph Walkable[\"Tick: Course.walkable\"]\n            walkable[\"fn.Course.walkable\"]\n        end\n        subgraph Graph[\"Tick: Course.graph\"]\n            graph[\"fn.Course.graph\"]\n        end\n        subgraph Summary[\"Tick: Course.summary\"]\n            summary[\"fn.Course.summary\"]\n        end\n    end\n\n    holes -->|holes| holeGeometry\n    unresolvedHoles -->|unresolved| holeGeometry\n    canonical -->|raster| holeGeometry\n    holeGeometry --> geometry[\"px.course.holes\"]\n    remaining -->|remaining| obstacleMap\n    components -->|fields| obstacleMap\n    baskets -->|baskets| obstacleMap\n    tees -->|tees| obstacleMap\n    canonical -->|raster| obstacleMap\n    obstacleMap --> obstacles[\"px.course.obstacles\"]\n    obstacles -->|obstacles| walkable\n    walkable --> walkableCells[\"px.course.walkable\"]\n    geometry -->|geometry| graph\n    obstacles -->|obstacles| graph\n    walkableCells -->|walkable| graph\n    graph --> courseGraph[\"px.course.graph\"]\n    courseGraph -->|graph| summary\n    geometry -->|geometry| summary\n    summary --> courseSummary[\"px.course.summary\"]\n",
  "S7.round.args.json": "{}\n",
  "S7.round.mmd": "flowchart TD\n    graph[\"px.course.graph\"]\n    courseSummary[\"px.course.summary\"]\n\n    subgraph Round[\"PCR: S7.round\"]\n        subgraph Legs[\"Tick: Round.legs\"]\n            legs[\"fn.Round.legs\"]\n        end\n        subgraph Path[\"Tick: Round.path\"]\n            path[\"fn.Round.path\"]\n        end\n        subgraph Summary[\"Tick: Round.summary\"]\n            summary[\"fn.Round.summary\"]\n        end\n    end\n\n    graph -->|graph| legs\n    legs --> roundLegs[\"px.round.legs\"]\n    roundLegs -->|legs| path\n    graph -->|graph| path\n    path --> roundPath[\"px.round.path\"]\n    roundPath -->|path| summary\n    roundLegs -->|legs| summary\n    courseSummary -->|course| summary\n    summary --> roundSummary[\"px.round.summary\"]\n"
});

/** One embedded flowchart, by its file name under src/lab/stages. */
export function readStageSource(name) {
  const text = STAGE_TEXT[name];
  if (text === undefined) throw new Error(`lab: '${name}' is not an embedded stage document.`);
  return text;
}
/** The same document, parsed as JSON. */
export function readStageSourceJson(name) { return JSON.parse(readStageSource(name)); }

/** The Mermaid path of one invented Stage: its flowchart, compiled and lowered to a document readPql can read. */
export function compiledStage(stage, compileMermaidPcr, lowerToPql, labDocument) {
  const compiled = compileMermaidPcr(readStageSource(`${stage}.mmd`), readStageSourceJson(`${stage}.args.json`));
  const { document, local } = lowerToPql(compiled);
  return { compiled, local, document: labDocument(document) };
}
