#!/usr/bin/env python3
"""Census of address-like string literals in ``pyto/``.

Walks the tree, finds quoted strings that look like dotted addresses, parses
them with ``pyto.address`` and reports what the round-five rule would call a
violation.  It enforces nothing: it prints a table and writes it to
``experiments/tasks/2/census.md``.

A hit is any quoted region on a line whose whole content matches the address
regex.  The three quote kinds (``'``, ``"``, ``` ` ```) are scanned separately
and merged, so an address quoted inside a quote of another kind still counts.

The rule and its sources are in ``src/pyto/address.py``'s docstring.
"""

from __future__ import annotations

import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from pyto.address import ROOTS, RESERVED_SECOND, check, parse  # noqa: E402

OUT = ROOT / "experiments" / "tasks" / "2" / "census.md"

SKIP_DIRS = {"reference", "node_modules", ".venv", "build", "__pycache__", ".git"}
SUFFIXES = {".py", ".js", ".mjs", ".json", ".yaml", ".md"}

# The task's regex, applied to the *contents* of a quoted string.
ADDRESS_RE = re.compile(r"^(?:[a-z][a-zA-Z0-9_-]*)(?:\.[a-zA-Z0-9_-]+)+$")

# Quoted-string scanners, one per quote kind: '...', "...", `...`.  Each kind
# is scanned over the whole line independently and the results are merged, so a
# quoted address nested inside a quote of another kind (a backticked address
# inside a double-quoted sentence, say) is counted.  A single alternation would
# read only the outermost region and miss it.
QUOTE_RES = (
    re.compile(r"'([^'\n]*)'"),
    re.compile(r'"([^"\n]*)"'),
    re.compile(r"`([^`\n]*)`"),
)


def walk(root: Path):
    for path in sorted(root.rglob("*")):
        if not path.is_file() or path.suffix not in SUFFIXES:
            continue
        if any(part in SKIP_DIRS for part in path.relative_to(root).parts):
            continue
        if path.resolve() == OUT.resolve():
            continue  # never census our own output; the count must be stable
        yield path


def is_evidence(rel: Path) -> bool:
    return "evidence" in rel.parts


def collect(root: Path):
    """Return (hits, files_scanned).  A hit is (literal, rel_path, lineno, ev)."""
    hits = []
    scanned = 0
    for path in walk(root):
        scanned += 1
        rel = path.relative_to(root)
        ev = is_evidence(rel)
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for lineno, line in enumerate(text.splitlines(), start=1):
            seen: set[tuple[int, str]] = set()
            for quote_re in QUOTE_RES:
                for match in quote_re.finditer(line):
                    literal = match.group(1)
                    if not ADDRESS_RE.match(literal):
                        continue
                    key = (match.start(1), literal)
                    if key in seen:
                        continue  # same region found by two quote kinds
                    seen.add(key)
                    hits.append((literal, rel.as_posix(), lineno, ev))
    return hits, scanned


def table(headers, rows) -> list[str]:
    out = ["| " + " | ".join(headers) + " |",
           "| " + " | ".join("---" for _ in headers) + " |"]
    for row in rows:
        out.append("| " + " | ".join(str(c) for c in row) + " |")
    return out


def report(hits, scanned) -> str:
    main = [h for h in hits if not h[3]]
    evid = [h for h in hits if h[3]]

    lines: list[str] = []
    lines.append("# Address census (task 2)")
    lines.append("")
    lines.append(
        f"Generated by `scripts/address_census.py`. Scanned {scanned} files "
        f"({', '.join(sorted(SUFFIXES))}) under `pyto/`, skipping "
        f"{', '.join(sorted(SKIP_DIRS))}. A hit is a quoted string whose whole "
        "content matches `^(?:[a-z][a-zA-Z0-9_-]*)(?:\\.[a-zA-Z0-9_-]+)+$`. The "
        "three quote kinds (`'`, `\"`, `` ` ``) are scanned separately and "
        "merged (de-duplicated by position), so an address quoted inside a "
        "quote of another kind is counted too. "
        "Literals under an `evidence/` directory are counted separately "
        "throughout. This describes; it enforces nothing."
    )
    lines.append("")
    lines.append(
        f"Totals: **{len(hits)}** address-like literals "
        f"({len(set(h[0] for h in hits))} distinct) in "
        f"{len(set(h[1] for h in hits))} files -- "
        f"{len(main)} outside `evidence/`, {len(evid)} inside."
    )
    lines.append("")
    lines.append(
        "Caveat, and it is a large one: the regex matches any dotted lowercase "
        "token in quotes, so this table mixes real PxC addresses (`px.badges.px`, "
        "`scratch.*`, `input.*`) with strings that were never addresses -- "
        "file names (`core.py`, `adapters.js`), attribute paths (`sys.path`, "
        "`time.time`), package names and dotted keys. The census does not try to "
        "tell them apart; a root not in `ROOTS` here means *the string does not "
        "look like a round-five address*, not *someone wrote a bad address*. "
        "It under-counts too, in two ways with one cause: quotes are paired "
        "left to right within a line, so an apostrophe in prose swallows a "
        "following address quoted with the same character -- and a doubled "
        "delimiter pairs with itself, so in an RST literal written with two "
        "backticks the first backtick pairs with the second and the third "
        "with the fourth and the address between them is never read, which "
        "is why the address examples in the module docstring of "
        "`src/pyto/address.py` are invisible to this census."
    )
    lines.append("")

    # Per root.
    lines.append("## Per root")
    lines.append("")
    roots = sorted(
        {parse(h[0]).root for h in hits},
        key=lambda r: (-sum(1 for h in hits if parse(h[0]).root == r), r),
    )
    rows = []
    for r in roots:
        sel = [h for h in hits if parse(h[0]).root == r]
        m = [h for h in sel if not h[3]]
        e = [h for h in sel if h[3]]
        known = "yes" if r in ROOTS else "no"
        rows.append((f"`{r}`", known, len(m), len({h[1] for h in m}),
                     len(e), len({h[1] for h in e})))
    lines += table(
        ["root", "in ROOTS", "literals (non-evidence)", "files",
         "literals (evidence)", "files"],
        rows,
    )
    lines.append("")

    # Reserved second segments under px.
    lines.append("## Reserved second segments under `px`")
    lines.append("")
    rows = []
    for seg in sorted(RESERVED_SECOND):
        sel = [h for h in hits if parse(h[0]).root == "px" and parse(h[0]).second == seg]
        other = [h for h in hits
                 if parse(h[0]).root != "px" and parse(h[0]).second == seg]
        m = [h for h in sel if not h[3]]
        e = [h for h in sel if h[3]]
        rows.append((f"`px.{seg}.*`", len(m), len(e), len({h[1] for h in sel}),
                     len(other)))
    lines += table(
        ["reserved second segment", "literals (non-evidence)",
         "literals (evidence)", "files", "same segment under another root"],
        rows,
    )
    lines.append("")

    # Rejected literals, grouped by root.
    rejected = [h for h in hits if check(h[0])]
    lines.append("## Literals `check()` rejects, by root")
    lines.append("")
    lines.append(
        f"{len(rejected)} of {len(hits)} literals are rejected "
        f"({len({h[0] for h in rejected})} distinct)."
    )
    lines.append("")
    by_root: dict[str, list] = defaultdict(list)
    for h in rejected:
        by_root[parse(h[0]).root].append(h)
    for r in sorted(by_root, key=lambda r: (-len(by_root[r]), r)):
        group = by_root[r]
        m = [h for h in group if not h[3]]
        e = [h for h in group if h[3]]
        lines.append(
            f"### root `{r}` -- {len(m)} non-evidence, {len(e)} evidence, "
            f"{len({h[0] for h in group})} distinct"
        )
        lines.append("")
        lines.append(f"Why: {'; '.join(check(group[0][0]))}")
        lines.append("")
        counts = Counter(h[0] for h in group)
        rows = []
        for literal, n in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])):
            ex = [h for h in group if h[0] == literal][:3]
            rows.append((f"`{literal}`", n,
                         "; ".join(f"{h[1]}:{h[2]}" for h in ex)))
        lines += table(["literal", "count", "up to three examples"], rows)
        lines.append("")

    return "\n".join(lines) + "\n"


def crosscheck(root: Path, hits) -> str:
    """Compare against the stress test's numbers (`questions.md:125-129`)."""
    ga = root / "experiments" / "grouped-ablation"

    def quoted_prefix(token: str, base: Path) -> int:
        """Occurrences of an opening quote plus ``token`` plus address chars.

        Every readable file, not just ``SUFFIXES`` -- this is the measure that
        reproduces the stress test, so it is kept deliberately loose.
        """
        pattern = re.compile(r"[\"'`]" + re.escape(token) + r"[a-zA-Z0-9_.-]*")
        n = 0
        for path in sorted(base.rglob("*")):
            if not path.is_file():
                continue
            if any(part in SKIP_DIRS for part in path.parts):
                continue
            if path.resolve() == OUT.resolve():
                continue
            try:
                n += len(pattern.findall(path.read_text(encoding="utf-8")))
            except (UnicodeDecodeError, OSError):
                continue
        return n

    def lit(root_name: str, base_rel: str | None = None):
        sel = [h for h in hits if parse(h[0]).root == root_name]
        if base_rel is not None:
            sel = [h for h in sel if h[1].startswith(base_rel)]
        return sum(1 for h in sel if not h[3]), sum(1 for h in sel if h[3])

    ga_rel = "experiments/grouped-ablation"
    m_main, m_ev = lit("material")
    m_ga_main, m_ga_ev = lit("material", ga_rel)
    s_main, s_ev = lit("scratch", ga_rel)
    i_main, i_ev = lit("input", ga_rel)
    s_repro = quoted_prefix("scratch.", ga)
    i_repro = quoted_prefix("input.", ga)

    lines = ["## Cross-check against the stress test (`questions.md:125-129`)", ""]
    lines += table(
        ["stress test claim", "its number", "this census, whole quoted literals "
         "in grouped-ablation (non-evidence + evidence)",
         "reproduction: quoted `<root>.` occurrences in grouped-ablation, all "
         "file types", "agreement"],
        [
            ("bare `scratch.`", 526, f"{s_main} + {s_ev} = {s_main + s_ev}",
             s_repro, "exact" if s_repro == 526 else f"off by {s_repro - 526}"),
            ("`input.`", 113, f"{i_main} + {i_ev} = {i_main + i_ev}",
             i_repro, "exact" if i_repro == 113 else f"off by {i_repro - 113}"),
            ("`material.<sha>` in `materials.py:39,222`", 2,
             f"{m_ga_main} + {m_ga_ev} = {m_ga_main + m_ga_ev}", "n/a",
             "agree on the finding, not on the count"),
        ],
    )
    lines.append("")
    lines.append(
        "**scratch: exact agreement, and it identifies what the stress test "
        "measured.** Counting an opening quote followed by `scratch.` and address "
        "characters, over every readable file under "
        "`experiments/grouped-ablation/`, gives "
        f"{s_repro} -- the stress test's 526 to the digit. So its number is "
        "occurrences of a quoted `scratch.`-prefixed token, not distinct "
        "addresses and not whole literals; most of them are keys inside the "
        "regenerated evidence JSON, which is why this census reports them "
        "separately."
    )
    lines.append("")
    lines.append(
        "**input: near agreement, off by "
        f"{i_repro - 113} ({i_repro} against 113).** The same measure that lands "
        "scratch exactly overshoots here. Two candidate reasons, neither checked "
        "against the stress test's own script, which is not in the tree: the "
        "grouped-ablation evidence was regenerated by `a5404b1` (\"evidence "
        "regenerated\"), so a count taken before it read a different tree; and "
        "`input.` also appears as an ordinary attribute access, which a "
        "hand-written grep may have excluded and this one does not."
    )
    lines.append("")
    lines.append(
        "**material: agreement on the finding, not reachable as a count.** The "
        f"literal census finds {m_ga_main + m_ga_ev} `material.*` literals in "
        "`experiments/grouped-ablation/`, because the store's address is never "
        "written as a literal: it is built by f-string at "
        "`experiments/grouped-ablation/materials.py:39` and "
        "`experiments/grouped-ablation/materials.py:222` "
        "(`address = f\"material.{key}\"`). The stress test cited those two lines "
        "rather than a count, and this census confirms them by their absence. "
        f"The {m_main + m_ev} `material.*` literal(s) the census does find live "
        "elsewhere in the tree (see the `material` group above; task 2's own test "
        "fixture is one of them) and are not the store. This is the census's main "
        "blind spot: every computed address is invisible to it."
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    hits, scanned = collect(ROOT)
    text = report(hits, scanned) + "\n" + crosscheck(ROOT, hits)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
