/**
 * The map of the port, as Parts: what is built, what is stubbed and why, what is
 * next and for what -- plus the findings, each with its `for`. Built by running
 * everything the port can run, so the map never claims an address the run did
 * not write. `node src/lab/map.js` rebuilds it and writes the store.
 */
import { createLab, finding } from './lab.js';
import { registerS0, runS0 } from './s0.js';
import { registerS1, runS1, s1YamlDocument, s1MermaidDocument } from './s1.js';
import { registerS2, runS2 } from './s2.js';
import { registerS3, runS3 } from './s3.js';
import { registerHolesNearest, runHolesNearest } from './holes-nearest.js';
import { registerCourse, runCourse } from './s7course.js';
import { registerRound, runRound } from './s7round.js';
import { registerRoute, runRoute } from './route.js';
import { registerPath, pathDocument, putCourses } from './path.js';
import { fixtureCapture, fixtureBasis } from './fixtures.js';

export function buildMap() {
  const lab = createLab();
  registerS0(lab); registerS1(lab); registerS2(lab); registerS3(lab); registerHolesNearest(lab); registerCourse(lab); registerRound(lab); registerRoute(lab); registerPath(lab);
  // The course fixture: the S0..S3 capture plus the two elements the later Stages
  // need -- a hole whose basket is missing, and structure no Stage object owns.
  const fixture = { hole11: true, obstacle: true };
  lab.put('px.exp.lab.fixture.basis', fixtureBasis(fixture));
  const s0 = runS0(lab, { decoded: fixtureCapture(20260911, fixture), label: 'lab course fixture capture' });
  const s1 = runS1(lab, { croppedImage: s0.croppedImage, document: s1YamlDocument(lab), seedRaster: true });
  const s2 = runS2(lab);
  const s3 = runS3(lab);
  const s4 = runHolesNearest(lab);
  const s5 = runCourse(lab);
  // The straight round first, so the searched round can be compared against what it replaces.
  const round = runRoute(lab, { course: 'labfixture' });
  const s6 = runRound(lab, { compareWith: 'labfixture' });
  putCourses(lab, ['DashsTrack']);
  const path = pathDocument(lab, { course: 'dashstrack', name: 'route', from: 'h1', to: 'h9' });
  lab.run(path.composition.PrincipleComponentRender, path.composition);
  for (const name of ['S0', 'S1', 'S2', 'S3', 'S3.quick-anno', 'HolesByNearestAnchor', 'HolesByNearestAnchor.invariants', 'S7.course', 'S7.course.invariants', 'S7.round', 'S7.round.invariants', 'S7.vs-straight', round.composition.PrincipleComponentRender, path.composition.PrincipleComponentRender]) lab.saveRecord(name);

  lab.put('px.exp.lab.map', {
    for: 'what the ChainSpot S0..S3 port and the Stages invented on top of it reached in one sprint, and what they did not',
    built: lab.addresses().filter(address => address.startsWith('px.exp.lab.')),
    ran: [
      { what: 'S0', document: 'the compiled S0.mmd plus the cache Tick S0.pcr.yaml names last', evidence: 'tests/lab-s0.test.js' },
      { what: 'S1', document: "the LAB's own PrincipleComponentRender.yaml, read by readPql", evidence: 'tests/lab-s1.test.js' },
      { what: 'S2', document: 'the document its three OperationSpecs declare, on S1 produce', evidence: 'tests/lab-s2.test.js' },
      { what: 'S3', document: 'the document its three OperationSpecs declare, plus the Python analogue\'s two-Tick accounting PCR', evidence: 'tests/lab-s3.test.js' },
      { what: 'HolesByNearestAnchor (invented, a fallback)', document: 'Hole.readNumbers -> Hole.bindAnchors -> Hole.assemble -> Hole.unplaced over the S1/S2/S3 produce Parts, plus its invariants PCR; superseded by the tee-to-badge ray the owner set as S5/S6, kept because a course where no ray resolves still has to say something', evidence: 'tests/lab-holes-nearest.test.js' },
      { what: 'S7 Pathfinding, the course half (invented)', document: 'Course.holeGeometry -> Course.obstacleMap -> Course.walkable -> Course.graph -> Course.summary; the obstacle map is a five-class partition of every pixel of the canonical raster and terrain is what no Stage object owns; stages/S7.course.mmd compiles to the same document', evidence: 'tests/lab-s7course.test.js' },
      { what: 'S7 Pathfinding, the round half (invented)', document: "Round.legs -> Round.path -> Round.summary, an A* over the course's walkable cells (integer costs 10/14, octile heuristic, no corner cutting, ties by (f, g, cell), no clock and no random), plus S7.round.invariants and the S7.vs-straight comparison with the route task 114 landed; stages/S7.round.mmd compiles to the same document", evidence: 'tests/lab-s7round.test.js' },
      { what: 'mermaid', document: 'S1.mmd compiles to the same document as the YAML (structural digest)', evidence: 'tests/lab-mermaid.test.js' },
      { what: 'pathfinding (the course)', document: 'Anchors -> Order -> Route -> Settle over the Stage Parts: badges order the holes, tees and baskets anchor them', evidence: 'tests/lab-route.test.js' },
      { what: 'pathfinding (the hex walk)', document: "Anchors -> Start -> Search -> Settle over a course manifest; kept as the LAB's human-in-the-loop tool for a raster no Stage has read yet", evidence: 'tests/lab-path.test.js' }
    ],
    stubbed: [
      { address: 'px.exp.lab.s1.whitedigits.model', why: "the LAB matches digits with a logistic model asset fitted on a corpus this repository does not have; the port normalizes the same way and matches template Parts built from the fixture's own glyph shapes" },
      { address: 'px.exp.lab.oracle.*', why: 'no recorded LAB values to check against: S0/S1 read chainspot-corpus/dev/DashsTrack/DashsTrack-full.jpg, absent here, and the Mermaid experiment records no generated output ("no generated output from this revision exists yet")' },
      { address: 'px.exp.lab.route.<course> for a real course', why: 'a route needs Stage outputs, and the Stages need a capture: the only capture here is the fixture, so DashsTrack is routed by the manifest hex walk and not by its own badges, baskets and tees' },
      { address: 'px.exp.lab.s2.recovery', why: "the LAB's S2 receipt says 'recovery: NOT RUN'; a fused or missing shell has no second chance in the clean path either" },
      { address: 'px.exp.lab.round.<course> for a real course', why: 'the round is searched over the fixture, the only capture this repository has; on a real capture the obstacle map would be a photograph of trees and water rather than one bar drawn to be unclaimable' },
      { address: 'px.exp.lab.round.legs[].points, smoothed', why: 'a leg is the cell path A* found, so an unobstructed leg still costs about 7% more than its straight line; a line-of-sight pass over the cells (string pulling) would remove that, and it is not written -- the number is reported in px.exp.lab.s6.vsstraight instead of being hidden' },
      { address: 'px.exp.lab.course.obstacles cost surface', why: 'every walkable cell costs the same. A real course map distinguishes fairway, rough, water and out of bounds, and the grid already has the shape for a cost per cell; nothing here can tell those apart, so nothing here pretends to' },
      { address: 'px.exp.lab.path.truth', why: 'the LAB anchors T/N/B come from the annotation truth file, which needs the corpus; the port searches the blind per-hole viewport the manifest itself carries' }
    ],
    next: [
      { what: 'a cost per cell instead of a boolean, and a leg that prefers fairway', for: 'the course half already classifies every pixel; the only reason walkable is 0 or 1 is that the fixture has one kind of obstacle' },
      { what: 'a line-of-sight smoothing pass over a leg', for: 'an unobstructed leg pays about 7% for being a cell path, and the comparison Part measures exactly that' },
      { what: 'S4 recovery, S5 the tee-to-badge ray, S6 the straight holes', for: "the owner's numbering (2026-09-11): a tee points at its badge and three points make a line, so a hole is resolved by geometry the picture carries rather than by nearest-anchor distance; S7 pathfinding then runs on those holes" },
      { what: 'run the TypeScript S1 on the same fixture and compare value by value', for: 'the port is proved structurally and by invariant, never against the LAB running' },
      { what: 'an `into: []` effect Calculation, or an oc. equivalent in the JS core', for: 'S0 cache is a Tick the studio cannot express without inventing a Part' },
      { what: 'a binding that reads a sibling result with no address', for: "the Mermaid S0's FullImage locality is a property the studio's grammar cannot hold" },
      { what: 'a Basket recovery path', for: "the LAB's S2 receipt says 'recovery: NOT RUN'; a fused or missing shell has no second chance yet" },
      { what: 'one corpus capture through S0..S3 and then the route', for: 'the route would then be a real round on a real course, and every Stage would have a value oracle' }
    ]
  });

  finding(lab, 'pql.directresult', { kind: 'friction', for: 'a Stage whose point is that a big intermediate is never published cannot be ported without publishing it', text: "The LAB's Mermaid compiler binds a Calculation's result directly: `with: { image: { kind: 'fn', ref: 'decode' } }`. S0's FullImage is never a Part, and the LAB's proof checks exactly that (compare.ts `fullImageLocal`, proof.ts `!generated.pxc.has('px.source.fullImage')`). The studio's PQL binds addresses only.", workaround: 'lowerToPql mints one address per unpublished result (px.exp.lab.s0.local.decode) and reports it.', proposal: 'a binding kind that names a sibling Calculation in the same Tick, or a Part the record marks Tick-local.' });
  finding(lab, 'pql.effecttick', { kind: 'friction', for: "S0's third Tick exists to write a cache, and the grammar has no way to say so", text: "The LAB's S0_CACHE_TICK declares `produces: []`. The studio's readPql refuses it: 'a Calculation that publishes nothing has no place in this grammar'.", workaround: 'fn.lab.s0.cachefullimage publishes a cache receipt Part instead.', proposal: 'allow an empty `into` for a Calculation whose effect the receipt records, the way pyto marks oc. Calculations.' });
  finding(lab, 'pql.occurrenceid', { kind: 'friction', for: 'comparing two runs Calculation by Calculation needs a name that survives an edit', text: "The Mermaid compiler gives every Calculation the graph's node id, and the LAB's runner names values and failures by it ('failed at decode'). PQL gives a Calculation no id; exec.js names it by position, call and into.", workaround: 'the port compares by position, which is what proof.ts does too.', proposal: 'an optional `id` on a Calculation, carried into the receipt and the run record.' });
  finding(lab, 'stage.s0hasnopql', { kind: 'strength', for: 'knowing which LAB documents are compositions and which are descriptions', text: "S0 has no PQL document in ChainSpot: S0.pcr.yaml is a description (input / sanitation / transform / output / last / receipt) and the composition is three OperationSpecs executed by the gateway. The only PQL documents on this tip are S1/exp/badge-assembly/PrincipleComponentRender.yaml and what the Mermaid compiler emits. The port therefore compiles S0.mmd and appends the cache Tick the description names last." });
  finding(lab, 'exec.carriedtheport', { kind: 'strength', for: 'what the studio core already had that the LAB needed', text: "readPql takes its parser explicitly, so the LAB's YAML ran unedited once a 120-line reader existed. classifyTick's chain rule is the LAB's own rule (every S1 Tick is a chain: selectHsvMask -> group8Connected, and the five-Calculation BadgeAssembly). Multi-`into` carried the search Tick that publishes the next search state and the path in one pass." });
  finding(lab, 'oracle.nocorpus', { kind: 'friction', for: 'an oracle is what turns a port into a proof', text: 'Nothing in the LAB records an expected value this port could check against: S0 and S1 read a corpus image that is not in this repository, and the Mermaid experiment is explicitly unrun ("compilation, tests, execution and rendering await review"). The port is checked by structure (compiled document equals the YAML by digest), by the LAB\'s own invariants (owned, muted and remaining partition the raster) and by a fixture built to the LAB\'s knobs.', workaround: 'a deterministic synthetic capture whose badges are drawn to the plate/border/digit geometry the S1 knobs accept.', proposal: 'ask for one corpus image and one recorded S1 run; both paths then compare value by value the way proof.ts does.' });
  finding(lab, 'search.noobjective', { kind: 'finding', for: 'what pathfinding means in the LAB before anyone writes a search', text: "`lab traverse` renders the current point and its six hex neighbours (270/330/30/90/150/210 at one radius) and an agent picks one; `lab search` keeps trails, pins, pages and an event log. There is no objective function and no expansion: the search is the eye in the loop. The port keeps the geometry exactly and names the objective (fewest hex moves to within tolerance of a target anchor, inside the raster), so a path becomes a produce with a receipt and replays as `lab traverse move <n>` commands.", proposal: 'if the LAB wants an automatic search, the objective belongs in the course manifest beside the blind viewport.' });
  finding(lab, 'course.oneholetable', { kind: 'friction', for: 'a search needs anchors, and six of the seven courses have none', text: 'Of the seven course manifests only DashsTrack carries a per-hole sourceBox table; the others name an image, aliases and sweep cases. The port refuses a course with no viewport table the way `lab scope hN` does, and searches a second manifest it owns.' });
  finding(lab, 'pql.fanout', { kind: 'friction', for: 'a Stage that computes one object per member of a family cannot say so in a document', text: "The LAB's S2 Tick `Basket.findPx` invokes `fn.Basket.findPx` once per shell member inside one Tick, and its receipt lists every invocation. A PQL document names a Calculation once, with one `into`, so the port's Calculation maps over the members and publishes the array.", workaround: 'fn.lab.basket.findpx takes the whole shell family and returns the Basket objects.', proposal: 'a Calculation that fans out over a collection input, each invocation its own line in the receipt.' });
  finding(lab, 'stage.specsaredocuments', { kind: 'strength', for: 'porting a Stage that has no YAML', text: "S2's composition is three OperationSpecs, each declaring consumes, produces and its one Calculation. That is a PQL document in another notation: the port writes it out (four Ticks with the substrate publish in front) and runs it unchanged. The same move works for S0; only S1 keeps a written PQL document." });
  finding(lab, 'route.objectivefromstages', { kind: 'finding', for: 'what pathfinding means once the Stages have run', text: 'The hex walk had to invent an objective because the LAB has none. The Stages give one: S1 reads the hole numbers, S2 finds the baskets, S3 the visible tees, so a path is the round itself -- each hole tee to basket in badge order, then basket to the next tee. The anchors come from the produce Parts, not from the course manifest, and the fixture proves the order is the reading and not the raster position (badge "01" is played before badge "10", which sits higher in the image).' });
  finding(lab, 'route.straightlegs', { kind: 'friction', for: 'a round is measured today, not routed', text: 'The legs are straight lines between anchors. The Stages already publish the obstacle information a real leg would respect (px.remaining.afterBadges, and the exact Basket and Tee pixels), and nothing consumes it yet.', workaround: 'the leg carries its length and refuses an anchor outside the canonical raster.', proposal: 'a Route Tick that reads px.remaining.afterBadges as cost and searches it, with the hex walk as its move set.' });
  finding(lab, 's3.badgemute', { kind: 'strength', for: 'why the Stages have to run in order', text: "S3's fixture finds four enclosed holes: two tee glyphs and two badge digit holes. The two digit holes are removed by S1's Badge mute footprint, which is the only reason S3's family vote sees a clean pair. Run S3 without S1 and the same detector produces a different family: the order S0 -> S1 -> S2 -> S3 is load-bearing, not administrative." });
  finding(lab, 's3.pythonoracle', { kind: 'strength', for: 'an oracle for a Stage with no recorded values', text: "The Python analogue (experiments/quick-anno-python/s3.py at 6309ff1) is an accounting PCR over S3's own output: enclosed = elongated + diamondDropped, elongated = candidates + excludedByBadge, candidates = measured + unframed, measured = familyMembers + votedOutOfFamily, familyMembers = tees. The port runs it as its own two-Tick composition (the second Tick consuming the first's published Part, the shape S3_CHECKPOINT.md describes) and the balance holds on the fixture." });
  finding(lab, 's4.ruleliftedintoastage', { kind: 'finding', for: 'what changes when a rule stops being a step of a search and becomes a Stage', text: "The straight route (task 114) binds each hole to the nearest free tee and basket inside its Order Tick. S4 is that same rule with nothing else around it, and the difference is that it can now be checked: the binding publishes its pools (every anchor with the hole that took it), so `everyTeeOnce`, `everyBasketOnce` and `everyBadgeOnce` are arithmetic over a published Part rather than a property of a function nobody can see into. The rule did not get better; it got inspectable, which is what a Tick boundary is for." });
  finding(lab, 's4.missingisnotaguess', { kind: 'strength', for: 'the one thing a hole assembler must never do', text: "Hole 11 of the course fixture has a badge and a tee and no basket, because the fixture draws no third basket. S4 reports `basket: null`, `missing: ['basket']`, confidence 0.75 out of a stated sum, and lists the hole under `px.holes.unplaced.incomplete` with the reason. The alternative every nearest-neighbour binder reaches for -- take the nearest basket even though another hole already has it, or interpolate one -- is refused by two invariants at once (`everyBasketOnce` and `missingIsNotGuessed`), and the test proves both refuse it.", proposal: 'a recovery Tick could look for a basket S2 missed, but it would publish a candidate with its own confidence, not fill this field.' });
  finding(lab, 'fixture.statedbasis', { kind: 'friction', for: 'a synthetic fixture with no stated basis can be tuned until the Stage passes', text: 'Every Stage here is checked against a capture this port drew. That is only honest if the capture says what each element answers to, so `fixtureBasis()` is a Part: the background values are chosen to fall outside both S1 masks (never <= 45, never >= 210), the badge geometry is the plate knobs, the basket is the LAB sprite inside a 4px shell, the tee is the elongated enclosed hole, and the obstacle is drawn outside every S1/S2/S3 predicate on purpose so that no Stage object can own it.', proposal: 'one corpus capture would replace the whole argument with a value oracle (proposal.lab.oracle.nocorpus).' });
  finding(lab, 's5.terrainisaresidue', { kind: 'finding', for: 'where an obstacle map comes from when no Stage was ever asked to find obstacles', text: "S5 detects nothing. It classifies every pixel of the canonical raster by which Stage already owns it -- badge (not in px.remaining.afterBadges), basket, tee -- and calls what is left over AND still dark in S1's own black mask `terrain`. On the course fixture that is exactly the 4224 pixels of the drawn bar and not one pixel more, because every basket and tee pixel leaves through its own door first. An obstacle map is a residue of the Stages, and the Stage that produces it is the one that says every pixel leaves once." });
  finding(lab, 's5.walkablerulestated', { kind: 'friction', for: 'the one judgement in S5 that the raster cannot settle', text: "Four of the five classes are printed on a map: a badge, a basket and a tee are symbols, and a tee or a basket is where a leg ENDS, so making them obstacles would make every leg unreachable. Only terrain blocks. That is a choice about what the picture means, not a fact about the pixels, so it is carried in the Part (`px.course.graph.walkableRule`) rather than buried in a predicate.", proposal: 'a real course would classify terrain further (water, trees, out of bounds) and give each class a cost instead of a boolean; the cell grid already has the shape for it.' });
  finding(lab, 's5.blockedbeforerouted', { kind: 'strength', for: 'what a course can say before anything searches it', text: "S5's edges carry `straightIsBlocked`, sampled at half a cell along the straight line between anchors. On the course fixture two of the three edges are blocked -- the walk from basket-2 back to tee-2 and the play of hole 10 -- which is the whole of S6's problem stated before S6 exists, and the reason the S6 landing can be compared against the straight route rather than merely admired." });
  finding(lab, 's6.themapiswhatchanged', { kind: 'finding', for: 'what the straight route got wrong, measured rather than asserted', text: "The straight route (task 114) and S6 bind the same holes to the same tees and baskets in the same order -- `sameHoles` and `sameAnchors` in px.exp.lab.s6.vsstraight are both true. The straight route was never wrong about WHERE the round goes; it was wrong about the ground in between: two of its three legs pass through four obstacle cells, and on the course fixture respecting the map costs 316.2 px on 1170.4 (+27%), almost all of it on one play leg (+72%). That is the whole difference between a round that is measured and a round that is walked." });
  finding(lab, 's6.gridoverhead', { kind: 'friction', for: 'what a cell path costs even when nothing is in the way', text: "The leg that nothing blocks (hole 1, tee-3 to basket-2) still comes out 6.7% longer than its straight line, because the path is a sequence of cell centres at 16px and an A* on a grid can only move in eight directions. That is not the obstacle map costing anything; it is the discretisation. It is reported per leg as `detourRatio` rather than smoothed away, so a reader can tell the two costs apart.", proposal: 'a line-of-sight pass (string pulling) over the cells would return the straight line where the straight line is walkable, and only bend where it is not.' });
  finding(lab, 's6.unreachableisaresult', { kind: 'strength', for: 'the answer a search must be allowed to give', text: "A basket with no walkable path to it makes a leg with `reachable: false`, no cells, no length, the reason, and the count of cells the search did reach; the round carries it under `unreachable` and its length excludes it. The invariant `unreachableIsReportedNotStraightened` refuses the alternative -- a straight line drawn across the thing that blocked it -- and the test builds a sealed room to prove the refusal fires." });
  finding(lab, 's6.determinismisdesigned', { kind: 'strength', for: 'a search that has to give the same answer on two machines', text: "Integer step costs (10 orthogonal, 14 diagonal) and an octile heuristic in the same units mean no float ever decides an ordering; the frontier is chosen by (f, g, cell index), which is a total order, and the eight moves are visited in a fixed order. No clock, no random, no Map insertion order. Two independent runs of the whole Stage produce the same cells, the same cost and the same length, which is the test." });
  finding(lab, 'stage.inventedinthelabgrammar', { kind: 'finding', for: 'whether the LAB\'s stage grammar carries a Stage it never wrote', text: "S4, S5 and S6 are not ports: nothing in ChainSpot corresponds to them. They were written in the LAB's own grammar anyway -- a contract naming consumes and produces, Ticks whose names are the OperationSpecs, one published Part per Calculation, a `has` provenance block on each constructed object, an accounting PCR as the oracle where no reference run exists, and a .mmd that compiles to the same document. Every one of those fitted without being bent. The one thing the grammar did not carry is the choice S5 had to make about what an obstacle IS, which is why that choice is a field in the Part rather than a predicate in the code." });
  finding(lab, 'holes.nearestisafallback', { kind: 'finding', for: 'why the first rule this port invented for assembling a hole is kept but not numbered', text: "The nearest-free-anchor binding was built as \"S4\" and then superseded on the same day: the owner's numbering makes S4 recovery, S5 the tee-to-badge ray (a tee POINTS at its badge), S6 the straight holes (three points make a line, so the basket is on the ray beyond the badge) and S7 pathfinding. The difference is not a refinement, it is a different kind of claim: nearest-anchor is a guess that is always available, the ray is evidence the picture actually carries and is sometimes absent. So the fallback keeps its Stage shape and its invariants under the name HolesByNearestAnchor, unnumbered, and the two rules disagreeing on a hole is a thing a reader can see rather than a thing that never happens.", proposal: 'when both run, publish the disagreement as its own Part: a hole the ray resolved one way and the distance another is the most interesting object on the course.' });
  finding(lab, 's1.recognition', { kind: 'friction', for: 'the one Calculation of S1 that is reduced rather than ported', text: 'fn.s1.whiteDigits.prepare/match segment glyphs with knobs and score them with a logistic model asset (digits/logisticInference, assets/logistic.json). The port normalizes to the same digitW x digitH grid and scores against template Parts; the reading shape (value, status, per-digit rankings) is the LAB\'s.' });
  lab.save('lab');
  return lab;
}

if (process.argv[1] && process.argv[1].endsWith('map.js')) { const lab = buildMap(); console.log(`px.exp.lab.map built: ${lab.get('px.exp.lab.map').built.length} Parts, ${lab.addresses().filter(a => a.startsWith('proposal.lab.')).length} findings`); }
