/** Declared review requirements; never claims automatic human acceptance. */
export const reviewItems = [
  { id: 'domain', label: 'Shared domain & Shelf', parts: [
    { id: 'identity', reviewId: 'identity', label: 'Manufacturer + mold + physical disc identity', action: { href: '#/shelf', label: 'Inspect Shelf' }, verification: 'Edit once, then inspect the same disc on the Course.' },
    { id: 'bags', reviewId: 'bags', label: 'Named bags use shared physical-disc references', action: { href: '#/shelf', label: 'Inspect membership' }, verification: 'Add one disc to two bags; removing membership must not delete it.' },
    { id: 'persistence', reviewId: 'persistence', label: 'Drafts, photos and changes survive reload', action: { href: '#/shelf', label: 'Inspect saving' }, verification: 'Download/reload a draft; samples are labelled and optional flight values remain optional.' }
  ] },
  { id: 'presentations', label: 'Composition & OnTheCourse', parts: [
    { id: 'bindings', reviewId: 'bindings', label: 'Every field is discoverable; identity text is editable', action: { href: '#/components?node=maker', label: 'Edit manufacturer' }, verification: 'Move or restyle Manufacturer and Mold; add a custom domain field.' },
    { id: 'reuse', reviewId: 'reuse', label: 'One presentation works for Single and DiscBattle', action: { href: '#/components', label: 'Edit the shared design' }, verification: 'Inspect the shared Card and Course output after a preset edit. Ported painter art is reused; generic card node geometry stays on the existing presentation Calculation.' },
    { id: 'footage', reviewId: 'footage', label: 'Compose on footage, export a transparent overlay', action: { href: '#/course', label: 'Inspect Course' }, verification: 'Background footage and editor selection must never appear in the exported PNG.' },
    { id: 'frame', reviewId: 'frame', label: 'Landscape and vertical export frames', action: { href: '#/course', label: 'Inspect the canvas control' }, verification: 'Route: OnTheCourse \u2192 the inspector\u2019s Canvas control (Landscape 1920 \u00d7 1080 / Vertical 1080 \u00d7 1920) and the Background / frame section under it. Switching the canvas changes the shape and the size label of the preview stage; a frame preset draws its fill, its title strip and a sponsor lockup taken from the cards cascade\u2019s global tokens, and the cards are fitted inside the safe area it leaves. \u201cSave overlay PNG \u2193\u201d then writes a file at exactly that size, and the export receipt carries width, height, orientation and framePresetId. One fn.overlay.frame Calculation composes the frame and the same fn.overlay.svg draws it: there is no second renderer. Raised by Boone (AI PM).' },
    { id: 'states', reviewId: 'states', label: 'Independent states, scores, highlights and winner', action: { href: '#/course', label: 'Inspect comparison states' }, verification: 'Duplicate a state, edit scores, return to the earlier state. Scores are not Disc properties.' }
  ] },
  { id: 'infrastructure', label: 'Constraints, PxC & feedback', parts: [
    { id: 'experiences', reviewId: 'experiences', label: 'Experience frame: UDS usable on #/experiences with photo/paint variants', action: { href: '#/experiences', label: 'Open the Experience frame' }, verification: 'Open #/experiences: six Experience Parts discovered from px.studio.experiences — UDS usable, the other five defined with their existing views linked and integration honestly pending. Select the Paint variant: the effective definition composes through fn.studio.effectiveDefinition via PQL (no view-layer merge), and selection publishes frame context under px.studio.uds.context.* on USE only — the prefix is empty after load. Add a disc: Paint is the default (no file needed), the picker offers exactly chevron-run, pressed-fern and contour-basin, the recipe previews live and rerolls only on request, and a blank recipe label stays live -- the disc’s current maker and mold name the artwork at render time (typed text is a fixed override), and one disc.create carries depiction and recipe with the specimen; Cancel creates nothing. The shelf inspector switches depiction with one undoable entity.set, keeping both sources. Verified: 278/278 node tests (13 UDS tests, including the live label: null renders the disc’s current maker/mold, so a pre-release named later renames the card with the recipe untouched, while a typed label is a fixed override); serial fixture regenerated with byte-identical SVGs; scripts/browser_test.py gained frame/composer/cancel/switch checks but no browser was available here, so browser verification is pending, not claimed. docs/experiences.md and CLOUD-START.md carry the frame contract; human acceptance remains open.' },
    { id: 'constraints', reviewId: 'constraints', label: 'PutterWarz composes reusable rules', action: { href: '#/competition', label: 'Inspect rule results' }, verification: 'Bag ≤5; exactly 1 mold; exactly 3 throws/team/completed round. Open rounds show pending.' },
    { id: 'trace', reviewId: 'trace', label: 'Real PQL path and memoized Parts are inspectable', action: { href: '#/components?trace=1', label: 'Inspect PxC' }, verification: 'Inspect px.render.*.art/card/svg and the existing 24-slot px.memo.* Parts; repeat unchanged inputs, then edit a preset binding to inspect invalidation. experiments/card-render/RESULTS.md retains the original cold/warm tradeoff and unresolved browser pixels. New opt-in Node pilot: experiments/shadow-render/README.md. Its separate worker checks captured requests after primary delivery; all 26 checked examples agree on JSON outputs/SVG, excluding execution traces. The deliberate mismatch remains recorded and routes the next 25 requests to reference; budget exhaustion and timeout never become agreement. Inspect evidence/shadow-render/control/REPORT.md, events.json and addressed Parts to follow capture, selection, delivery, comparison and routing through existing PxC/PQL. The separate signature intervention is at experiments/signature-intervention/README.md; its observer-free lazy/eager timing arms and separately instrumented work count are fixture-scoped only. run-03 retains directional timing and independently dispatched edited worlds, which are not parity evidence; verification-05 captures one explicit shared edited-world sequence, retains both runRecord receipts and PQL-compares 39 JSON-visible/SVG observations. Its instrumented copies are output-neutral. No Studio UI/export default changes, no deployment, no pixel-parity claim and no human acceptance.' },
    { id: 'feedback', reviewId: 'feedback', label: 'Item comments persist and export with checkpoint identity', action: { href: '#/components', label: 'Return to editor' }, verification: 'This checklist is neat’s review-handoff component with local item comments. Nothing auto-accepts work.' },
    { id: 'record', reviewId: 'record', label: 'The composition exports its own pyto-run-record@1 and opens a Tick render', action: { href: '#/course?trace=1', label: 'Inspect the run record' }, verification: 'Route: OnTheCourse with the sample workspace (DiscBattle, three discs) → Inspect PxC ↗. “Export run record ↓” downloads a pyto-run-record@1 the shared validator accepted and keeps it as the Part px.run.on-the-course (14 Ticks, 14 invocations); “Open Tick render ↗” saves a standalone page with one section per Tick. The same composition also runs with parallel: true (runtime.sceneParallel, one Tick per stage): its record carries parallel, per-invocation placement, per-Tick latency_ms and budget exactly as pyto.materialize.run_record writes them, and the saved page draws the branches of that Tick side by side. Verified: npm test, node --test pyto/viewer/test/*.test.mjs, and scripts/browser_test.py --embedded, whose new block runs the studio on a real local origin and opens the saved page over file:// with zero network requests. Deployed build: scripts/build.mjs now copies pyto/viewer/ into dist/ because src/app.js and src/runtime.js import it directly; npm run build confirms dist/pyto/viewer/ exists. The deployed page itself has not been opened in a browser.' },
    { id: 'receipts', reviewId: 'receipts', label: 'The studio reads its own receipts through PQL, and undo is one more Calculation on the record', action: { href: '#/course?trace=1', label: 'Inspect the Receipts section' }, verification: 'Route: OnTheCourse with the sample workspace \u2192 Inspect PxC \u2197 \u2192 the Receipts section. The list is not an index the page keeps: it is the Calculation fn.studio.receipts binding the prefix query px.receipt.* and publishing two Parts from one pass (px.studio.receipts and px.studio.receipts.summary), so several `into` per Calculation and the query are both exercised by the page that shows them. One row per receipt: name, consumes, produces, and a result digest that labels the material identity of that receipt\u2019s invocations, not the bytes of its Parts. \u201c\u21b6 Undo last change\u201d in the Shelf inspector pops px.undo.studio through fn.undo.pop and fn.undo.settle, restores the exact previous px.studio.world, and leaves px.receipt.studio-undo behind for the same list to show; an undo with an empty stack changes nothing and is still recorded. Verified: npm test, node --test pyto/viewer/test/*.test.mjs, and scripts/browser_test.py --embedded, whose checks now number 12 (the eleventh drives the Undo button and compares the rendered rows against px.receipt.* in the store; the twelfth runs the same sample composition with parallel: true and reads the schedule off the exported record; scripts/review_checkpoint.mjs pins that count).' },
    { id: 'algorithm-references', reviewId: 'algorithm-references', label: 'Next calculates one Tick; retained Frames show actual PxC Parts', action: { href: '/public/algorithm-references/index.html', label: 'Open live algorithm references' }, verification: 'Default perceptron: first Next gives products 1 and -1 and sum 0.25; activation/output remain absent. Second Next gives output 1. Back/scrub only review; changed inputs fork and preserve the old run. Try the four-step tree and five-step transformer, inspect Part addresses and query-row/attended-token-column attention, then export or replay a retained record. 256 package tests, 142 viewer tests, build and headless Chrome reference checks pass. Evidence and the served build fingerprint: test-results/algorithm-references-live. Source base 455f66db91fc34ac0d8d32b66aa6ccbef224b774 plus uncommitted work. Legacy Studio Python browser harness unavailable (missing playwright); history is page-lifetime. Automated verification; no human acceptance.' },
    { id: 'id3-digits', reviewId: 'id3-digits', label: 'ID3 grows a tree from visible digit examples and pixel questions', action: { href: '/public/algorithm-references/index.html#digit-lab', label: 'Watch ID3 learn' }, verification: 'One full-screen tree with one sample/question card per actual node. Compare questions opens the top-right dialog; alternate previews leave the learned tree unchanged. Try a digit and Inspect open optional lenses. Back/scrub retain history; Fit tree, zoom and Current node navigate. 262 package tests and six focused ID3 tests pass; local full learner has 50 Ticks/25 nodes, training 30/30 and held-out 10/20 on disjoint small teaching sets. Bounded reduced-motion Chrome profiling measured one HTML replacement and 7 height flushes by Tick 6 after removing redundant renders, versus three replacements and 19 flushes before; timings are directional evidence, not machine-specific gates. Browser results, screenshots and served build fingerprint: test-results/algorithm-references-id3/verification.json. Human review remains open.' }
  ] }
];
