/** Declared review requirements; never claims automatic human acceptance. */
export const reviewItems = [
  { id: 'domain', label: 'Shared domain & Shelf', parts: [
    { id: 'identity', reviewId: 'identity', label: 'Manufacturer + mold + physical disc identity', action: { href: '#/shelf', label: 'Inspect Shelf' }, verification: 'Edit once, then inspect the same disc on the Course.' },
    { id: 'bags', reviewId: 'bags', label: 'Named bags use shared physical-disc references', action: { href: '#/shelf', label: 'Inspect membership' }, verification: 'Add one disc to two bags; removing membership must not delete it.' },
    { id: 'persistence', reviewId: 'persistence', label: 'Drafts, photos and changes survive reload', action: { href: '#/shelf', label: 'Inspect saving' }, verification: 'Download/reload a draft; samples are labelled and optional flight values remain optional.' }
  ] },
  { id: 'presentations', label: 'Composition & OnTheCourse', parts: [
    { id: 'bindings', reviewId: 'bindings', label: 'Every field is discoverable; identity text is editable', action: { href: '#/components?node=maker', label: 'Edit manufacturer' }, verification: 'Move or restyle Manufacturer and Mold; add a custom domain field.' },
    { id: 'reuse', reviewId: 'reuse', label: 'One presentation works for Single and DiscBattle', action: { href: '#/components', label: 'Edit the shared design' }, verification: 'Inspect the shared Card and Course output after a preset edit. Ported painter art is reused; generic card node geometry stays on the existing presentation Calculation.' },
    { id: 'footage', reviewId: 'footage', label: 'Compose on footage, export a transparent overlay', action: { href: '#/course', label: 'Inspect Course' }, verification: 'Background footage and editor selection must never appear in the exported PNG.' },
    { id: 'states', reviewId: 'states', label: 'Independent states, scores, highlights and winner', action: { href: '#/course', label: 'Inspect comparison states' }, verification: 'Duplicate a state, edit scores, return to the earlier state. Scores are not Disc properties.' }
  ] },
  { id: 'infrastructure', label: 'Constraints, PxC & feedback', parts: [
    { id: 'constraints', reviewId: 'constraints', label: 'PutterWarz composes reusable rules', action: { href: '#/competition', label: 'Inspect rule results' }, verification: 'Bag ≤5; exactly 1 mold; exactly 3 throws/team/completed round. Open rounds show pending.' },
    { id: 'trace', reviewId: 'trace', label: 'Real PQL path and memoized Parts are inspectable', action: { href: '#/components?trace=1', label: 'Inspect PxC' }, verification: 'Inspect px.render.*.art/card/svg and the fn.disc.format.shelfSheet PQL calculation; repeat unchanged inputs to confirm reuse and deterministic SVG bytes.' },
    { id: 'feedback', reviewId: 'feedback', label: 'Item comments persist and export with checkpoint identity', action: { href: '#/components', label: 'Return to editor' }, verification: 'This checklist is neat’s review-handoff component with local item comments. Nothing auto-accepts work.' },
    { id: 'record', reviewId: 'record', label: 'The composition exports its own pyto-run-record@1 and opens a Tick render', action: { href: '#/course?trace=1', label: 'Inspect the run record' }, verification: 'Route: OnTheCourse with the sample workspace (DiscBattle, three discs) → Inspect PxC ↗. “Export run record ↓” downloads a pyto-run-record@1 the shared validator accepted and keeps it as the Part px.run.on-the-course (14 Ticks, 14 invocations); “Open Tick render ↗” saves a standalone page with one section per Tick. The same composition also runs with parallel: true (runtime.sceneParallel, one Tick per stage): its record carries parallel, per-invocation placement, per-Tick latency_ms and budget exactly as pyto.materialize.run_record writes them, and the saved page draws the branches of that Tick side by side. Verified: npm test, node --test pyto/viewer/test/*.test.mjs, and scripts/browser_test.py --embedded, whose new block runs the studio on a real local origin and opens the saved page over file:// with zero network requests. Deployed build: scripts/build.mjs now copies pyto/viewer/ into dist/ because src/app.js and src/runtime.js import it directly; npm run build confirms dist/pyto/viewer/ exists. The deployed page itself has not been opened in a browser.' },
    { id: 'receipts', reviewId: 'receipts', label: 'The studio reads its own receipts through PQL, and undo is one more Calculation on the record', action: { href: '#/course?trace=1', label: 'Inspect the Receipts section' }, verification: 'Route: OnTheCourse with the sample workspace \u2192 Inspect PxC \u2197 \u2192 the Receipts section. The list is not an index the page keeps: it is the Calculation fn.studio.receipts binding the prefix query px.receipt.* and publishing two Parts from one pass (px.studio.receipts and px.studio.receipts.summary), so several `into` per Calculation and the query are both exercised by the page that shows them. One row per receipt: name, consumes, produces, and a result digest that labels the material identity of that receipt\u2019s invocations, not the bytes of its Parts. \u201c\u21b6 Undo last change\u201d in the Shelf inspector pops px.undo.studio through fn.undo.pop and fn.undo.settle, restores the exact previous px.studio.world, and leaves px.receipt.studio-undo behind for the same list to show; an undo with an empty stack changes nothing and is still recorded. Verified: npm test, node --test pyto/viewer/test/*.test.mjs, and scripts/browser_test.py --embedded, whose checks now number 12 (the eleventh drives the Undo button and compares the rendered rows against px.receipt.* in the store; the twelfth runs the same sample composition with parallel: true and reads the schedule off the exported record; scripts/review_checkpoint.mjs pins that count).' }
  ] }
];
